INSERT INTO COURSES VALUES(1,'Web & Mobile 1',6);
INSERT INTO COURSES VALUES(2,'Web & Mobile 2',6);
INSERT INTO COURSES VALUES(3,'System Analysis & Design',6);
INSERT INTO COURSES VALUES(4,'IT Project Management',6);
INSERT INTO COURSES VALUES(5,'Principles of Information System',6);
INSERT INTO COURSES VALUES(6,'Production and Operations Management',6);
INSERT INTO COURSES VALUES(7,'SDP 1',3);
INSERT INTO COURSES VALUES(8,'SDP 2',3);
INSERT INTO COURSES VALUES(9,'Dancing in the rain',1);